### ISSUE TITLE
fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [sergv/htoml-parse#1]
```
       Building library for htoml-parse-0.1.0.1..                 
       [1 of 1] Compiling Data.Toml.Parse                                                                                                                                                                                                                               
       /var/stackage/work/unpack-dir/unpacked/htoml-parse-0.1.0.1-2572ace2faa183afc596bbdb8cf3ebfb7934ae5c1225ed1d4d6e0d4f6b04a0d7/s
rc/Data/Toml/Parse.hs:273:10: error: [GHC-76037]                                                                                    
           Not in scope: type constructor or class ‘MonadPlus’                                                                      
           |                                                                                                                        
       273 | instance MonadPlus Validation                                                                                          
           |          ^^^^^^^^^                                                                                                     
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/htoml-parse-0.1.0.1-2572ace2faa183afc596bbdb8cf3ebfb7934ae5c1225ed1d4d6e0d4f6b04a0d7/s
rc/Data/Toml/Parse.hs:280:48: error: [GHC-76037]                                                                                    
           Not in scope: type constructor or class ‘MonadPlus’                                                                      
           |                                                                                                                        
       280 |   deriving (Functor, Applicative, Alternative, MonadPlus)                                                              
           |                                                ^^^^^^^^^
```
